
pub const REGISTERS: [Register; 27] = [
    Register::R15(15, "r15"),
    Register::R14(14, "r14"),
    Register::R13(13, "r13"),
    Register::R12(12, "r12"),
    Register::Rbp(6, "rbp"),
    Register::Rbx(3, "rbx"),
    Register::R11(11, "r11"),
    Register::R10(10, "r10"),
    Register::R9(9, "r9"),
    Register::R8(8, "r8"),
    Register::Rax(0, "rax"),
    Register::Rcx(2, "rcx"),
    Register::Rdx(1, "rdx"),
    Register::Rsi(4, "rsi"),
    Register::Rdi(5, "rdi"),
    Register::OrigRax(-1, "orig_rax"),
    Register::Rip(-1, "rip"),
    Register::Cs(51, "cs"),
    Register::Rflags(49, "eflags"),
    Register::Rsp(7, "rsp"),
    Register::Ss(52, "ss"),
    Register::FsBase(58, "fs_base"),
    Register::GsBase(59, "gs_base"),
    Register::Ds(53, "ds"),
    Register::Es(50, "es"),
    Register::Fs(54, "fs"),
    Register::Gs(55, "gs")
];

pub enum Register<'a> {
    Rax(i32, &'a str),
    Rbx(i32, &'a str),
    Rcx(i32, &'a str),
    Rdx(i32, &'a str),
    Rdi(i32, &'a str),
    Rsi(i32, &'a str),
    Rbp(i32, &'a str),
    Rsp(i32, &'a str),
    R8(i32, &'a str),
    R9(i32, &'a str),
    R10(i32, &'a str),
    R11(i32, &'a str),
    R12(i32, &'a str),
    R13(i32, &'a str),
    R14(i32, &'a str),
    R15(i32, &'a str),
    Rip(i32, &'a str),
    Rflags(i32, &'a str),
    Cs(i32, &'a str),
    OrigRax(i32, &'a str),
    FsBase(i32, &'a str),
    GsBase(i32, &'a str),
    Fs(i32, &'a str),
    Gs(i32, &'a str),
    Ss(i32, &'a str),
    Ds(i32, &'a str),
    Es(i32, &'a str),
}
